export const HS_CHAPTERS: Record<string, string> = {
  "01": "Animales vivos",
  "02": "Carne y despojos comestibles",
  "03": "Pescado, crustáceos y moluscos",
  "04": "Lácteos, huevos, miel y productos comestibles de origen animal",
  "05": "Los demás productos de origen animal",
  "06": "Plantas vivas y productos de la floricultura",
  "07": "Hortalizas, plantas, raíces y tubérculos",
  "08": "Frutas y frutos comestibles",
  "09": "Café, té, yerba mate y especias",
  "10": "Cereales",
  "11": "Productos de la molinería, malta, almidón",
  "12": "Semillas oleaginosas, plantas industriales",
  "13": "Gomas, resinas y demás jugos y extractos vegetales",
  "14": "Materias trenzables y demás productos de origen vegetal",
  "15": "Grasas y aceites animales, vegetales o microbianos",
  "16": "Preparaciones de carne, pescado o crustáceos",
  "17": "Azúcares y artículos de confitería",
  "18": "Cacao y sus preparaciones",
  "19": "Preparaciones a base de cereales, harina o almidón",
  "20": "Preparaciones de hortalizas, frutas y plantas",
  "21": "Preparaciones alimenticias diversas",
  "22": "Bebidas, líquidos alcohólicos y vinagre",
  "23": "Residuos y desperdicios de industrias alimentarias",
  "24": "Tabaco y sucedáneos del tabaco",
  "25": "Sal, azufre, tierras, piedras, yesos, cales y cementos",
  "26": "Minerales metalíferos, escorias y cenizas",
  "27": "Combustibles y aceites minerales (petróleo, gas, carbón)",
  "28": "Productos químicos inorgánicos",
  "29": "Productos químicos orgánicos",
  "30": "Productos farmacéuticos",
  "31": "Abonos y fertilizantes",
  "32": "Extractos curtientes, colorantes, pinturas y barnices",
  "33": "Aceites esenciales, perfumería y cosméticos",
  "34": "Jabones, agentes de superficie, lubricantes, ceras y velas",
  "35": "Albuminoides, colas, enzimas",
  "36": "Pólvoras, explosivos, artículos de pirotecnia",
  "37": "Productos fotográficos y cinematográficos",
  "38": "Productos diversos de las industrias químicas",
  "39": "Plásticos y sus manufacturas",
  "40": "Caucho y sus manufacturas",
  "41": "Pieles (excepto la peletería) y cueros",
  "42": "Manufacturas de cuero, marroquinería, artículos de viaje",
  "43": "Peletería y confecciones de peletería",
  "44": "Madera, carbón vegetal y manufacturas de madera",
  "45": "Corcho y sus manufacturas",
  "46": "Manufacturas de espartería y cestería",
  "47": "Pasta de madera y material fibroso celulósico",
  "48": "Papel, cartón y sus manufacturas",
  "49": "Libros, impresos, prensa y manuscritos",
  "50": "Seda",
  "51": "Lana y pelo fino u ordinario",
  "52": "Algodón",
  "53": "Demás fibras textiles vegetales, hilados de papel",
  "54": "Filamentos sintéticos o artificiales",
  "55": "Fibras sintéticas o artificiales discontinuas",
  "56": "Guata, fieltro, telas sin tejer, cuerdas y cordeles",
  "57": "Alfombras y demás revestimientos para el suelo",
  "58": "Tejidos especiales, encajes, tapicería, pasamanería",
  "59": "Telas impregnadas, recubiertas o estratificadas",
  "60": "Tejidos de punto",
  "61": "Prendas y complementos de vestir de punto",
  "62": "Prendas y complementos de vestir excepto de punto",
  "63": "Los demás artículos textiles confeccionados",
  "64": "Calzado, polainas y artículos análogos",
  "65": "Sombreros, tocados y sus partes",
  "66": "Paraguas, sombrillas, bastones y artículos similares",
  "67": "Plumas preparadas, flores artificiales, manufacturas de cabello",
  "68": "Manufacturas de piedra, yeso, cemento, amianto y mica",
  "69": "Productos cerámicos",
  "70": "Vidrio y sus manufacturas",
  "71": "Perlas, piedras preciosas, metales preciosos y bisutería",
  "72": "Fundición, hierro y acero",
  "73": "Manufacturas de fundición, hierro o acero",
  "74": "Cobre y sus manufacturas",
  "75": "Níquel y sus manufacturas",
  "76": "Aluminio y sus manufacturas",
  "78": "Plomo y sus manufacturas",
  "79": "Cinc y sus manufacturas",
  "80": "Estaño y sus manufacturas",
  "81": "Los demás metales comunes y sus manufacturas",
  "82": "Herramientas, artículos de cuchillería de metal común",
  "83": "Manufacturas diversas de metal común",
  "84": "Reactores nucleares, calderas, máquinas y aparatos mecánicos",
  "85": "Máquinas, aparatos y material eléctrico y electrónico",
  "86": "Vehículos y material para vías férreas",
  "87": "Vehículos automóviles, tractores, ciclos y demás terrestres",
  "88": "Aeronaves, vehículos espaciales y sus partes",
  "89": "Barcos y embarcaciones",
  "90": "Instrumentos de óptica, fotografía, medida, medicina y cirugía",
  "91": "Aparatos de relojería",
  "92": "Instrumentos musicales",
  "93": "Armas, municiones y sus partes",
  "94": "Muebles, mobiliario médico-quirúrgico, artículos de cama",
  "95": "Juguetes, juegos y artículos de deporte",
  "96": "Manufacturas diversas (bolígrafos, peines, botones, encendedores, pipas)",
  "97": "Objetos de arte, de colección o de antigüedad",
};

export function chapterHint(fraccion: string): string {
  const ch = fraccion.slice(0, 2);
  const desc = HS_CHAPTERS[ch];
  return desc ? `[Cap.${ch}: ${desc}]` : `[Cap.${ch}]`;
}
